#
# CC Creative Commons 2022
# Uznanie autorstwa - Bez utworów zależnych 4.0 Międzynarodowe
# Autor olios
#

# //------------------------\\
# |                          |
# |   Konfiguracja pluginu   |
# |                          |
# \\------------------------//

# WAŻNE!
# Każde zmiany w tym pliku wymagają przeładowania serwera lub jego restartu
# Usuwanie zmiennych spowoduje niepoprawne działanie pluginu
# Możesz pobrać oryginalnie, niemodyfikowane pliki ze stronie pluginu
# https://www.spigotmc.org/resources/authors/olios123.1116758/

# Dostaniesz powiadomienie gdy zostanie wypuszczona nowsza wersja pluginu
check-updates: true

# Język pluginu
# Możesz tworzyć własne pliki językowe .yml lub edytować już istniejące
language: en

# Logi pluginu będą wyświetlane w zielonym kolorze
clearer-logs: false

# Zapisuj wszystkie dane z plików do bazydanych (tylko MySQL)
# Spawdź plik database.yml aby zmienić informacje o połączeniu
database: false

# //------------------------\\
# |                          |
# |  Konfiguracja BackInPack |
# |                          |
# \\------------------------//

# Standardowa wielkość plecaka
# Minimalna wielkość to 1 (wartość 0 wyłącza plecak dla gracza), maksimum 54
# UWAGA: Zmiana tej opcji na mniejszą może spowodować wyrzucenie niektórych przedmiotów z plecaka
standard-backpack-size: 54 # default 54

# Tylko gracze którzy posiadają tą permisje będą mogli korzystać z plecaka
# Wpisz nazwę permisji lub wpisz false aby wyłączyć
backpack-permission: false
#backpack-permission: backinpack.gui

# Od tego ustawienia zależy co stanie się z przedmiotami po śmierci gracza
# Wybierz jedną z poniższych wartości:
# save - przedmioty zostają zachowane
# delete - przedmioty zostają usunięte z plecaka
# drop - przedmioty wypadają z gracza
player-dead: save # default save

# Wyślij informację o utraconych/wyrzuconych przedmiotach po śmierci
lost-items-message: true

# Tekstura plecaka
#
# Skąd zdobyć tekstury ?
# Wjedź na stronę https://minecraft-heads.com/ i wybierz jakąś głowę
# Zjedź na dół do sekcji "Other" i skopiuj poje "value"
# Skopiowany tekst wklej tutaj (nie martw się, będzie on dosyć długi)
# WAŻNE! Zmiana tej wartości wymaga restartu serwera - tekstura starych plecaków zostanie nie zmieniona
backpack-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODM1MWU1MDU5ODk4MzhlMjcyODdlN2FmYmM3Zjk3ZTc5NmNhYjVmMzU5OGE3NjE2MGMxMzFjOTQwZDBjNSJ9fX0="

#      Crafting
# +-----+-----+-----+
# |  1  |  2  |  3  |
# +-----+-----+-----+
# |  4  |  5  |  6  |
# +-----+-----+-----+
# |  7  |  8  |  9  |
# +-----+-----+-----+

# Numery odpowiadają miejscu w craftingu
# Wpisz ID przedmiotu
# Lista ID przedmiotów https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
# Wpisz "null" aby pozostawić pole puste
crafting:
  1: LEATHER
  2: LEATHER
  3: LEATHER
  4: LEATHER
  5: CHEST
  6: LEATHER
  7: LEATHER
  8: LEATHER
  9: LEATHER

# Styl plecaka
# Możesz tutaj edytować nazwę oraz opis plecaka
# ZMIANA TYCH DANYCH SPOWODUJE, ŻE POPRZEDNIE PLECAKI PRZESTANĄ DZIAŁAĆ!
backpack-style:
  name: "&e&lBackpack"
  title: "&e&lBackpack &f${player}" # Nazwa plecaka widziana w GUI | ${player} = nick gracza
  lore:
    - "&7(Right click to open)"

# Przedmiot niedostępnego miejsca w GUI plecaka
# Możesz edytować wygląd tego przedmiotu
backpack-inaccessible-place:
  TITLE: "&c&lx"
  MATERIAL: RED_STAINED_GLASS_PANE # jeżeli plugin nie znajdzie wskazanego przedmiotu użyje RED_STAINED_GLASS_PANE
  LORE: [] # wypisuj od nowej lini

# //------------------------\\
# |                          |
# |     Grupy plecaków       |
# |                          |
# \\------------------------//

# Grupy plecaków pozwalają na dostęp do różnych plecaków w różnych światach
# WAŻNE: Nie doprowadzaj do sytuacji, w której jeden świat należy do ponad JEDEN grupy
# WAŻNE: Może to całkowicie pozbawić plugin poprawnego działania
# WAŻNE: Po włączeniu tej opcji plik "inventories.yml" nie będzie używany
backpack-groups:
  enable: false # default false
  groups:
    group1: # Nazwa grupy może być dowolna, ale nie może się powtarzać, ale musi być inna niż "inventories"
      - world # Nazwa świata -> patrz pliki serwerowe
      - world_the_end
    group2:
      - world_nether

# Wielkość plecaka dla grup
# Podaj nazwę grupy zdefiniowaną powyżej i wpisz po dwukropku ilość miejsca
# Włączając tę opcję, możesz także korzystać z permisji "backinpack.size.[ilość miejsc].[nazwa grupy]"
backpack-group-size:
  enable: false # default false
  groups:
    group1: 54
    group2: 9

# //------------------------\\
# |                          |
# |   Opcje administratora   |
# |                          |
# \\------------------------//

# Zezwalaj administratorom na otwieranie plecaków innych graczy przy pomocy komendy /backpack [gracz]
admin-open-player-backpack: true

# Permisja wymagana do otworzenia plecaka innego gracza
admin-permission: backinpack.admin

# //------------------------\\
# |                          |
# |         Efekty           |
# |                          |
# \\------------------------//

# Gdy gracz otworzy plecak usłyszy dźwięk (Ender Chest Open)
open-sound: true

# Gdy gracz zamknie plecak usłyszy dźwięk (Ender Chest Close)
close-sound: true