#
# CC Creative Commons 2022-2023
# Attribution-NoDerivatives 4.0 International
# Author olios
#


#
#  _______  ___      __   __  _______  ___   __    _
# |       ||   |    |  | |  ||       ||   | |  |  | |
# |    _  ||   |    |  | |  ||    ___||   | |   |_| |
# |   |_| ||   |    |  |_|  ||   | __ |   | |       |
# |    ___||   |___ |       ||   ||  ||   | |  _    |
# |   |    |       ||       ||   |_| ||   | | | |   |
# |___|    |_______||_______||_______||___| |_|  |__|
#


# IMPORTANT!
# Any changes to this file require the server to be restarted.
# Removing variables will cause the plugin to malfunction.
# You can download the original, unmodified files from plugin page.
# https://www.spigotmc.org/resources/authors/olios123.1116758/


# *------------------------------------*
# :        CHECKING FOR UPDATES        :
# *------------------------------------*
# You will get a notification when a newer plugin version is released.
check-updates: true
# *------------------------------------*


# *------------------------------------*
# :          PLUGIN LANGUAGE           :
# *------------------------------------*
# Plugin language.
# You can create your own .yml language files or edit existing ones.
language: en
# *------------------------------------*


# *------------------------------------*
# :                LOGS                :
# *------------------------------------*
# The plugin logs will be displayed in green.
clearer-logs: false
# *------------------------------------*


# *------------------------------------*
# :               BACKUP               :
# *------------------------------------*
# Plugin will backup all files every 1h.
# Archives are saved in the /backup folder.
backup: true
# *------------------------------------*


# *------------------------------------*
# :               MYSQL                :
# *------------------------------------*
# Save all data from files to database (MySQL only).
# Check file database.yml to change connection information.
# Data in the database is synchronized with each change of plugin files (inventories.yml).
database: false

# How MySQL works.
# The database can perform not only the function of storing files, but also synchronizing backpacks between servers.
#
# Possible options to choose from:
# data - sends data to the database and stores it there
# sync - works the same as "data", but additionally synchronizes backpacks from the database between servers
database-type: data

# How to use the sync option:
# * You need two servers with the same version of the plugin.
# * Connect the plugin to the same database.
# * In "database-type" type "sync" in both configurations.
# * Restart the servers.
# * Ready!
#
# IMPORTANT! The "sync" option does not modify the inventories.yml file in any way.
# The file with this option will not be used.
# IMPORTANT! The sync option can significantly slow down the performance of the plugin.
#
# *------------------------------------*


#  _______  _______  __    _  _______  ___   _______  __   __  ______    _______  _______  ___   _______  __    _
# |       ||       ||  |  | ||       ||   | |       ||  | |  ||    _ |  |   _   ||       ||   | |       ||  |  | |
# |     __||   _   ||   |_| ||    ___||   | |    ___||  | |  ||   | ||  |  |_|  ||_     _||   | |   _   ||   |_| |
# |    |   |  | |  ||       ||   |___ |   | |   | __ |  |_|  ||   |_||_ |       |  |   |  |   | |  | |  ||       |
# |    |   |  |_|  ||  _    ||    ___||   | |   ||  ||       ||    __  ||       |  |   |  |   | |  |_|  ||  _    |
# |    |__ |       || | |   ||   |    |   | |   |_| ||       ||   |  | ||   _   |  |   |  |   | |       || | |   |
# |_______||_______||_|  |__||___|    |___| |_______||_______||___|  |_||__| |__|  |___|  |___| |_______||_|  |__|
#


# *------------------------------------*
# :       STANDARD BACKPACK SIZE       :
# *------------------------------------*
# Standard backpack size.
# Minimum size 1 (a value of 0 turns off the backpack), maximum 54.
# WARNING: Changing this option to a smaller one will cause some items to be thrown from the backpack.
standard-backpack-size: 54 # default 54
# *------------------------------------*


# *------------------------------------*
# :    MAXIMUM NUMBER OF BACKPACK      :
# *------------------------------------*
# The number of maximum number of backpacks can be set from 1 to 36.
# When a player has the maximum amount of backpacks, he will not be able to buy new ones and they will not be added to him.
# Reducing this number may result in REMOVAL OF EXCESSIVE backpacks already owned by players.
max-backpacks: 36
# *------------------------------------*


# *------------------------------------*
# :           FIRST BACKPACK           :
# *------------------------------------*
# Getting a backpack after joining the server.
# If the player enters the server for the first time, he will receive a backpack.
default-backpack: true
# *------------------------------------*


# *------------------------------------*
# :          BACKPACK ACCESS           :
# *------------------------------------*
# Access to backpacks.
# The content of backpacks can be accessed in several ways.
# If the value in "item" is changed, backpacks (as items) will not be removed but will stop working.
# The player will receive a message that they cannot open this backpack when they try to open it.
backpack-access:
  gui: true
  item: true


# Require permission for the player to access their backpack.
# If "true" player must have permission "backinpack.backpack-access".
backpack-permission: false
# *------------------------------------*


# *------------------------------------*
# :        BACKPACK AFTER DEATH        :
# *------------------------------------*
# This setting determines what happens to the items after the player dies.
# Player backpacks will NEVER BE DELETED.
# Select one of the following values:
# save - items are saved
# delete - items are removed from the backpack
# drop - items drop from the player
player-dead: save # default save

# Keep items with permission.
# Items will be saved upon player's death regardless of configuration as long as they have the permission listed below.
# "backinpack.backpack-save"

# Players other than the owner of the backpack cannot access it.
# *------------------------------------*


# *------------------------------------*
# :       CREATING NEW BACKPACKS       :
# *------------------------------------*
# Possibilities to create a backpack.
# Specifies how a backpack can be created and assigned to a player.
create-backpack:
  crafting: true # disabling this option will enable backpack assignment (section below)
  buy: true # disabling this option will disable the ability to purchase backpacks in the backpack GUI

# IMPORTANT: Assigning backpacks - section below.

# Standard name for new backpacks.
# The name will also be visible when crafting backpacks.
default-backpack-name: "New backpack"
# *------------------------------------*


# *------------------------------------*
# :          ASSIGN BACKPACKS          :
# *------------------------------------*
# If you don't want crafting a backpack to add a new backpack.
# You can use the option to assign created backpacks.
# Backpacks can still be crafted, but it won't result in adding another backpack.

# This option is enabled automatically if you checked "false" in line 172.

# The player can assign an empty backpack to the correct backpack.
# It's enough that after crafting he tries to open it and a menu with backpacks will be displayed.
# Must select one of them and the backpack will be assigned to the backpack as an item.

# The only way to get a new backpack will be to buy it or add it by the administration.

# GUI will be shown when assigning a backpack.
backpack-assigned-gui:
  title: "&eAssigning a backpack"

# *------------------------------------*


# *------------------------------------*
# :      BACKPACK TEXTURE (ITEM)       :
# *------------------------------------*
# Backpack texture.
#
# Where to get textures?
# Go to https://minecraft-heads.com/ and select a head.
# Scroll down to the "Other" section and copy the "value".
# Paste the copied text here (don't worry, it will be quite long).
# IMPORTANT! Changing this value requires a server restart - the texture of worn backpacks will not be changed.
backpack-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODM1MWU1MDU5ODk4MzhlMjcyODdlN2FmYmM3Zjk3ZTc5NmNhYjVmMzU5OGE3NjE2MGMxMzFjOTQwZDBjNSJ9fX0="
# *------------------------------------*


# *------------------------------------*
# :         CRAFTING A BACKPACK        :
# *------------------------------------*
# The numbers represent the crafting field.
# Enter the Item ID here.
# Item ID list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
# Type "null" to set it to empty.

#      Crafting
# +-----+-----+-----+
# |  1  |  2  |  3  |
# +-----+-----+-----+   =======>  +----------+
# |  4  |  5  |  6  |   =======>  | Backpack |
# +-----+-----+-----+   =======>  +----------+
# |  7  |  8  |  9  |
# +-----+-----+-----+

crafting:
  enable: true
  1: LEATHER
  2: LEATHER
  3: LEATHER
  4: LEATHER
  5: CHEST
  6: LEATHER
  7: LEATHER
  8: LEATHER
  9: LEATHER
# *------------------------------------*


# *------------------------------------*
# :           BACKPACKS MENU           :
# *------------------------------------*
# Here are the options for backpack list GUI.

# Item responsible for the ability to buy a backpack.
# You will be able to set the price and other selling options in the next section.

# Head texture that will be displayed as an item through which you can purchase a backpack.
buy-backpack-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA1NmJjMTI0NGZjZmY5OTM0NGYxMmFiYTQyYWMyM2ZlZTZlZjZlMzM1MWQyN2QyNzNjMTU3MjUzMWYifX19"

# Appearance of the item.
buy-backpack-style:
  TITLE: "&a&lPurchase of a backpack"
  LORE:
    - "&fBackpack size: &6%backinpack_config_backpack_buy_backpack_size% slots"
    - "&fPrice: &6%backinpack_config_backpack_buy_cost%$"
    # The true/false value will be replaced according to the language file in 184, 185 line of the file.
    - "&fYou will receive as item: %backinpack_config_backpack_buy_give_as_item%"
    - ""
    - "&7(Click to buy a backpack)"
# *------------------------------------*


# *------------------------------------*
# :         BUYING A BACKPACK          :
# *------------------------------------*
# Purchasing a backpack.
# The backpack can be purchased in the backpack menu.
# Sales can be enabled/disabled in line 173 of this file.
# IMPORTANT! Requires the Vault plugin to work.
# A backpack can also be added with /backpack give <player>
backpack-buy:
  backpack-size: 54 # Backpack size after purchase (from 1 to 54).
  cost: 500 # Purchase price.
  give-as-item: true # The backpack is also added as an item.
# *------------------------------------*


# *------------------------------------*
# :    BACKPACK APPEARANCE (OBJECT)    :
# *------------------------------------*
# Backpack style.
# Here you can define the name of the backpack and its description.
backpack-style:
  # The material will always be a head with a backpack texture.
  TITLE: "&e&l%backinpack_backpack_name%" # Name visible in the backpack GUI and backpacks list GUI.
  LORE:
    - "&fSize: &6%backinpack_backpack_size%"
    - "&fItems: &6%backinpack_backpack_items_count% items"
    - ""
    - "&7(Click to open)"
    - "&7(RMB Click to change name)"


# The appearance of the backpack that will be visible when the backpack needs to be assigned.
# For more information about this section, see line 186.
backpack-style-to-assignment:
  TITLE: "&7&lUnassigned backpack"
  MATERIAL: LEATHER
  LORE:
    - "&fClick to assign a backpack"
    - "&fThe backpack in this condition does not store items"


# Item of the inaccessible space in the backpack.
# You can edit the appearance of this item.
backpack-inaccessible-place:
  TITLE: "&c&lx"
  MATERIAL: RED_STAINED_GLASS_PANE # if the plugin doesn't find the material, it will use RED_STAINED_GLASS_PANE
  LORE: [] # write from dashes on a new line
# *------------------------------------*


# *------------------------------------*
# :         BLACKLIST OF ITEMS         :
# *------------------------------------*
# Prohibited items.
# Here you can specify what items players cannot store in their backpacks.
#
# How to write the names of items correctly using the example:
# If the item has color variants, e.g. shulker box, enter SHULKER_BOX (or in lower case).
# Replace spaces with => "_".
#
# Blacklist works in a keyword search way.
# If an item contains one of the names listed below in its id, excludes it.
# This makes it possible to exclude all colors, e.g. of shulker boxes or wool.
blacklist-items:
  - SHULKER_BOX # added as standard, so as not to increase the space in the backpack
# *------------------------------------*


#  _______  _______  __   __  __   __  _______  __    _  ______   _______
# |       ||       ||  |_|  ||  |_|  ||   _   ||  |  | ||      | |       |
# |     __||   _   ||       ||       ||  |_|  ||   |_| ||  _    ||  _____|
# |    |   |  | |  ||       ||       ||       ||       || | |   || |_____
# |    |   |  |_|  ||       ||       ||       ||  _    || |_|   ||_____  |
# |    |__ |       || ||_|| || ||_|| ||   _   || | |   ||       | _____| |
# |_______||_______||_|   |_||_|   |_||__| |__||_|  |__||______| |_______|


# *------------------------------------*
# :         DISABLED COMMANDS          :
# *------------------------------------*
# List of disabled commands.
# List command names with hyphens.
# IMPORTANT! Only enter the full command names, NOT their aliases.
disabled-commands: []
  #- backpack
# *------------------------------------*


#  _______  ______   __   __  ___   __    _
# |   _   ||      | |  |_|  ||   | |  |  | |
# |  |_|  ||  _    ||       ||   | |   |_| |
# |       || | |   ||       ||   | |       |
# |       || |_|   ||       ||   | |  _    |
# |   _   ||       || ||_|| ||   | | | |   |
# |__| |__||______| |_|   |_||___| |_|  |__|


# *------------------------------------*
# :    ACCESS TO PLAYERS' BACKPACKS    :
# *------------------------------------*
# Allow administrators to open other player's backpacks with the command /backpack [player]
admin-open-player-backpack: true

# For an administrator, to have access to players' backpacks, he must be an op or have the permission: "backinpack.open"
# *------------------------------------*


#  _______  _______  _______  _______  _______  _______  _______
# |       ||       ||       ||       ||       ||       ||       |
# |    ___||    ___||    ___||    ___||     __||_     _||  _____|
# |   |___ |   |___ |   |___ |   |___ |    |     |   |  | |_____
# |    ___||    ___||    ___||    ___||    |     |   |  |_____  |
# |   |___ |   |    |   |    |   |___ |    |__   |   |   _____| |
# |_______||___|    |___|    |_______||_______|  |___|  |_______|


# *------------------------------------*
# :               SOUNDS               :
# *------------------------------------*
# When the player open the backpack, he will hear a sound (Ender Chest Open).
open-sound: true

# When the player close the backpack, he will hear a sound (Ender Chest Close).
close-sound: true
# *------------------------------------*
